### ISSUE TITLE
show template source for fragments

### ISSUE THREAD

**Issue by grahamu** [pinax/pinax_theme_tester#22]
Some templates are not full pages and thus are rendered via "include" or templatetag. In these cases the source display shows template code which displays the include or templatetag, but not the actual fragment itself.

Keep the current source display for fragments, seeing the include or templatetag in context is useful.

Add some way to show the included fragment or a specific "pinax/templates/calendars/calendar.html" file source in the template path. In the case of templatetags perhaps there is some way of determining their related template? If not then a hard-coded file reference.

This is seen in `invitations`, `waitinglist`, `calendars`, among others.

**Comment by grahamu** [comment]
fixed by #23

**Comment by grahamu** [comment]
@paltman the solution I coded in #23 does the trick, but I wonder if semantic markup in the rendered template (encompassing the snippet includes and/or templatetags) might be simpler. `TemplateWithContextView` can process self.template_name, find specific markup, add those files to the display. For {% include %} that would save retyping the filename, for {% templatetag %} you'd still need to specify the source filename somehow in semantic markup or get super fancy with introspection. Just a thought for your consideration.

**Comment by paltman** [comment]
@grahamu I *think* I'm following you but not enough to provide any feedback.  Would need to see an example.
